# Run rustfmt with this config (it should be picked up automatically).
# We are supposed to follow the style used by rustc.
style_edition = "2024"
use_small_heuristics = "Max"
merge_derives = false
group_imports = "StdExternalCrate"
imports_granularity = "Module"
use_field_init_shorthand = true

# Files to ignore.
ignore = [
    "/build/",
    "/*-build/",
    "/build-*/",

    # Do not format tests.
    "rustc_public/tests",

    # Ignore build.rs.
    "rustc_public/build.rs",
]
