# Run a job to ensure formatting is OK
name: Format Check
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Rust Toolchain
        uses: dtolnay/rust-toolchain@nightly

      - name: Run Rust Format
        run: ./x fmt --check
