name: rustc-pull

on:
  workflow_dispatch:
  schedule:
    # Run at 04:00 UTC every day
    - cron: "0 4 * * *"

jobs:
  pull:
    if: github.repository == 'rust-lang/project-stable-mir'
    uses: rust-lang/josh-sync/.github/workflows/rustc-pull.yml@main
    with:
      github-app-id: ${{ vars.APP_CLIENT_ID }}
      pr-base-branch: main
      branch-name: rustc-pull
    secrets:
      github-app-secret: ${{ secrets.APP_PRIVATE_KEY }}
